name = "map-search-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "map-search-db"
database_id = "3511d3d1-290f-400a-9f00-b676bee730c8"
migrations_dir = "migrations"
